### ISSUE TITLE
Issue uploading bed file

### ISSUE THREAD

**Issue by ttj131** [beliveau-lab/PaintSHOP#11]
Hi, I've tried to upload a bed file to design probes for my genomic region. 

However, no matter how I change the bed file, the app does not run with the bed file. Is there any template for us to download and refer to?

Attached is my uploaded bed-like file for reference

Any help is greatly appreciated!

[chr1_gbanding.txt](https://github.com/beliveau-lab/PaintSHOP/files/10668086/chr1_gbanding.txt)

**Comment by conorcamplisson** [comment]
Hi @ttj131 , 

Here's a version of the file that works with PaintSHOP: [chr1_gbanding.txt](https://github.com/beliveau-lab/PaintSHOP/files/10760606/chr1_gbanding.txt)

I prepared it in Excel with this approach: 

* use three columns for the `chrom`, `start`, `stop`, data
* do NOT include a header row, start with the first region as the top row
* save the file as TAB-separated txt (can name it .bed or .txt)
* upload the file to PaintSHOP to query probes for each region

For reference, here's what the file looked like before/after this process. Before:

```
$ head chr1_gbanding.txt
chrom chromStart chromEnd
chr1 1 2300000
chr1 2300001 5300000
chr1 5300001 7100000
chr1 7100001 9100000
chr1 9100001 12500000
chr1 12500001 15900000
chr1 15900001 20100000
chr1 20100001 23600000
chr1 23600001 27600000
```

After formatting for PaintSHOP: 

```
$ head chr1_gbanding.txt
chr1    1       2300000
chr1    2300001 5300000
chr1    5300001 7100000
chr1    7100001 9100000
chr1    9100001 12500000
chr1    12500001        15900000
chr1    15900001        20100000
chr1    20100001        23600000
chr1    23600001        27600000
chr1    27600001        29900000
```

**Comment by ttj131** [comment]
Hi @conorcamplisson ,

Many thanks for the help along with the formatting, the tab delimited format and column headers were the issue and i've resolved it.
